### PR TITLE
Refactor Date into a lib, add fixed price option

### PR DESCRIPTION
**Pull request by simonv3**
# What's Changed
* Added fixed price to method call, to overwrite the final price output
* Moved Beardo.Date into a library file.

### CODE REVIEW

**Comment by bnvk** [comment]
Hrm, this currently breaks date filtering  as the module is not being loaded and declared in the right way...

```
/Users/brennannovak/Beardo/lib/beard_date.js:8
  var filter_date = args.options.date.replace(/-/g, '');
                    ^
ReferenceError: args is not defined
    at Object.Beardo.Date.full (/Users/brennannovak/Beardo/lib/beard_date.js:8:21)
    at /Users/brennannovak/Beardo/beardo.js:165:48
    at Function._.each._.forEach (/Users/brennannovak/Beardo/node_modules/underscore/underscore.js:145:9)
    at Object.Beardo.magickData (/Users/brennannovak/Beardo/beardo.js:161:5)
    at /Users/brennannovak/Beardo/beardo.js:316:32
    at null.<anonymous> (/Users/brennannovak/Beardo/node_modules/csv/node_modules/csv-parse/lib/index.js:63:16)
    at emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

I need to better learn how to modularize node stuff like this, but will get to it soon!

**Comment by simonv3** [comment]
Huh, I'll fiddle with this on Monday

**Comment by simonv3** [comment]
The module was being loaded properly, it's just that "args" isn't available in the lib unless you pass it to it. For the sake of functionality, I'm going to pass args to the function. It might be an idea to pass it to the Date instance when it gets instantiated.

**Comment by simonv3** [comment]
@bnvk let me know if the above work for you, I did some testing on my end and I think the problem should be fixed.

**Comment by bnvk** [comment]
Ah yes, it was just the args being passed into the module. Nice fix ;)

Hrm, now I'm getting this error...

```
/Users/brennannovak/Beardo/beardo.js:341
                return callback();
                       ^
TypeError: undefined is not a function
    at /Users/brennannovak/Beardo/beardo.js:341:24
    at Object.Beardo.summonUser (/Users/brennannovak/Beardo/beardo.js:110:12)
    at /Users/brennannovak/Beardo/beardo.js:334:22
    at null.<anonymous> (/Users/brennannovak/Beardo/node_modules/csv/node_modules/csv-parse/lib/index.js:63:16)
    at emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

**Comment by simonv3** [comment]
Totally my fault. That's a quick-fix to get the tests running (though will probably be useful in the future regardless), I made sure to only run callback when it's defined. 

Can you pull that down and tell me whether that works? If not, what command are you running?

**Comment by bnvk** [comment]
Annnnnnnd MERGED :+1: :grin:

**Comment by simonv3** [comment]
:trumpet: :notes:

**Pull request merged**
