### PR TITLE
Fix that borked PR

### PR DESCRIPTION
**Pull request by simonv3**
And now with tests for dates! 

One of the tests fails because I'm not sure whether when you pass "Apr" as a trim, it should just return stuff for *this* April, rather than *all* Aprils.

Thoughts @bnvk?

### CODE REVIEW

**Comment by bnvk** [comment]
@simonv3 aced! Well done compadre ;)

**Comment by simonv3** [comment]
@bnvk What are your thoughts on the failing test? Should a search for "Apr" return all Aprils? Or only Aprils of this year?

**Comment by bnvk** [comment]
@simonv3 thanks for asking for clarification. My initial instinct re: this is that we pass a second word like `-d april all` or parse a hyphen like `-d april-all` what do you think?

**Comment by simonv3** [comment]
Agreed. 

I think my expectation is (would be as an outsider too) that "April" would find the most recent April. However! It would have to be the most recent April in the past I think. So say "Jun" today would show me June of 2014, rather than doing June of this year - 2015.

**Comment by bnvk** [comment]
Right. Exactly. That's actually an interesting case (dates in past year) I'm not sure how the code handles at the moment. I actually wonder if we should investigate using another node library at this point or if moment.js will be sufficient

**Comment by simonv3** [comment]
I don't actually know any other date libraries. I can picture how to do this, and it wouldn't be overly complex in moment.

**Pull request merged**
